#!/bin/bash

WIFI_SSID="$( cat .broot-secret-wifi-ssid 2>/dev/null )"
WIFI_PSK="$( cat .broot-secret-wifi-psk 2>/dev/null )"

if [[ -z "${WIFI_SSID}" ]]; then
  read -p 'wifi ssid: ' WIFI_SSID
  echo -n "${WIFI_SSID}" > .broot-secret-wifi-ssid
fi

if [[ -z "${WIFI_PSK}" ]]; then
  read -p 'wifi psk: ' WIFI_PSK
  echo -n "${WIFI_PSK}" > .broot-secret-wifi-psk
fi
